# 正式运行的配置文件


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/graduate?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: myth
    password: ad
  jpa:
    show-sql: true
  thymeleaf:
    cache: false